apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: router-ex
  name: router-ex
  namespace: rpiuav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router-ex-replicaset
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: router-ex-replicaset
        app.kubernetes.io/name: router-ex-deployment
    spec:
      containers:
      - env:
        - name: RELEASE_NODE
          value: router_ex@router-ex
        - name: RELEASE_COOKIE
          value: router_ex_cookie
        - name: ROUTER_CONFIG
          valueFrom:
            configMapKeyRef:
              key: ROUTER_CONFIG
              name: rpi4-config
        image: ghcr.io/fancydrones/x500-cm4/router-ex:20251024-c86c6c5
        livenessProbe:
          exec:
            command:
            - /app/bin/router_ex
            - rpc
            - Process.whereis(RouterEx.RouterCore) != nil
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        name: router-ex
        ports:
        - containerPort: 5760
          name: tcp-mavlink
          protocol: TCP
        - containerPort: 14550
          name: udp-gcs
          protocol: UDP
        - containerPort: 14560
          name: udp-video0
          protocol: UDP
        - containerPort: 14561
          name: udp-video1
          protocol: UDP
        - containerPort: 14562
          name: udp-extra0
          protocol: UDP
        - containerPort: 14563
          name: udp-extra1
          protocol: UDP
        readinessProbe:
          exec:
            command:
            - /app/bin/router_ex
            - rpc
            - Process.whereis(RouterEx.RouterCore) != nil
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "0.5"
            memory: 500Mi
          requests:
            cpu: "0.25"
            memory: 100Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev/serial0
          name: serial0
      hostNetwork: true
      initContainers:
      - command:
        - sh
        - -c
        - echo "initContainer will delay startup by 20s to ensure serial device is
          ready" && sleep 20 && echo "exiting"
        image: busybox:1.34
        name: init-delay
      volumes:
      - hostPath:
          path: /dev/serial0
        name: serial0
