# Find latest image here: https://hub.docker.com/r/aler9/rtsp-simple-server/tags?page=1&name=rpi

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: streamer-deployment
    name: streamer
  name: streamer
  namespace: rpiuav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer-replicaset
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: streamer-replicaset
        app.kubernetes.io/name: streamer-deployment
    spec:
      containers:
        - env:
            - name: RTSP_PATHS_CAM_SOURCE
              value: "rpiCamera"
          image: bluenviron/mediamtx@sha256:18e39f7d81326bee3cca2d43f773ae491546fb4422ca4604c00760b18047bd6f
          name: streamer
          ports:
            - containerPort: 8554
            - containerPort: 8888
            - containerPort: 8889
          resources:
            limits:
              cpu: "2"
              memory: 2500Mi
            requests:
              cpu: "1"
              memory: 500Mi
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /run/udev
              name: udev
              readOnly: true
            - mountPath: /dev/shm
              name: temp
            - name: cam-conf
              mountPath: /rtsp-simple-server.yml # This should be your final destination
              subPath: rtsp-simple-server.yml
              readOnly: true
      hostNetwork: true
      volumes:
        - hostPath:
            path: /run/udev/
          name: udev
          readOnly: true
        - name: temp
          emptyDir: {}
        - name: cam-conf
          readOnly: true
          configMap:
            name: rpi4-config
            items:
              - key: STREAMER_CONFIG
                path: rtsp-simple-server.yml
