apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: streamer-deployment
    name: streamer
  name: streamer
  namespace: rpiuav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer-replicaset
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: streamer-replicaset
        app.kubernetes.io/name: streamer-deployment
    spec:
      containers:
      - env:
        - name: RTSP_PATHS_CAM_SOURCE
          value: "rpiCamera"
        image: aler9/rtsp-simple-server:v0.21.0-rpi
        name: streamer
        ports:
        - containerPort: 8554
        resources:
          limits:
            cpu: "2"
            memory: 2500Mi
          requests:
            cpu: "1"
            memory: 500Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run/udev
          name: udev
        - mountPath: /
          name: main-conf
      hostNetwork: true
      volumes:
      - configMap:
          items:
          - key: STREAMER_CONFIG
            path: rtsp-simple-server.yml
          name: rpi4-config
        name: main-conf
      - hostPath:
          path: /run/udev
        name: udev
        #readOnly: true
