apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: streamer-deployment
    name: streamer
  name: streamer
  namespace: rpiuav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer-replicaset
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: streamer-replicaset
        app.kubernetes.io/name: streamer-deployment
    spec:
      containers:
      - env:
        - name: RTSP_PATHS_CAM_SOURCE
          value: "rpiCamera"
        image: aler9/rtsp-simple-server:v0.21.0-rpi
        name: streamer
        ports:
        - containerPort: 8554
        - containerPort: 8888
        - containerPort: 8889
        resources:
          limits:
            cpu: "2"
            memory: 2500Mi
          requests:
            cpu: "1"
            memory: 500Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run/udev
          name: udev
        - mountPath: /dev/shm
          name: temp
        # - mountPath: /rtsp-simple-server.yml
        #   name: rtsp-simple-server
        #   subPath: rtsp-simple-server.yml
        - name: cam-conf
          mountPath: /etc/cfg/rtsp-simple-server.yml # This should be your final destination
          subPath: rtsp-simple-server.yml
      hostNetwork: true
      volumes:
      - hostPath:
          path: /run/udev/
        name: udev
        readOnly: true
      - name: temp
        emptyDir: {}
      # - configMap:
      #     #defaultMode: 420
      #     items:
      #     - key: STREAMER_CONFIG
      #       path: rtsp-simple-server.yml
      #     name: rtsp-simple-server
      #   name: rpi4-config
      - name: cam-conf # To access this volume, this name must be used inside volumeMounts of the container
        configMap:
          name: rpi4-config
          items:
            - key: STREAMER_CONFIG  # Name of the item we had used inside our ConfigMap (under data:)
              path: rtsp-simple-server.yml
