version: "3.9"
services:
  streamer:
    image: ghcr.io/fancydrones/x500-cm4/streamer:20221002-f3a1710
    ports:
    - 8554:8554
    volumes:
    - /run/udev:/run/udev:ro
    privileged: true
    restart: always
    environment:
      - CAMERA_PIPELINE0=
          libcamerasrc ! 
          video/x-raw,width=1280,height=720,format=NV12,colorimetry=bt601,interlace-mode=progressive ! 
          videoflip video-direction=180 ! 
          videorate ! 
          video/x-raw,framerate=30/1 ! 
          v4l2convert ! 
          v4l2h264enc output-io-mode=2 extra-controls="controls,repeat_sequence_header=1,video_bitrate_mode=1,h264_profile=3,video_bitrate=3000000" ! 
          video/x-h264,profile=main,level=(string)4 ! 
          queue max-size-buffers=1 name=q_enc ! 
          h264parse ! rtph264pay config-interval=1 name=pay0 pt=96
      - VIDEO_PORT=8554
  router:
    image: ghcr.io/fancydrones/x500-cm4/router:20221109-90362cf
    ports:
    - 5760:5760
    - 14560:14560
    - 14561:14561
    - 14562:14562
    - 14563:14563
    network_mode: host
    privileged: true
    restart: always
    volumes:
    - ./mavlink-router.conf:/etc/mavlink-router/main.conf
    - /dev/serial0:/dev/serial0
  announcer:
    image: ghcr.io/fancydrones/x500-cm4/announcer:20221109-3cdc41c
    network_mode: host
    restart: always
    environment:
      - CAMERA_URL=rtsp://10.10.10.99:8554/video0
      - CAMERA_ID=100
      - CAMERA_NAME=Main
      - SYSTEM_HOST=127.0.0.1
      - SYSTEM_PORT=14560
      - SYSTEM_ID=1
      - MAVLINK20=1
