# Project information
site_name: Fancydrones X500 RPi4
site_url: https://fancydrones.github.io/x500-rpi4/
site_author: Fancydrones // Roy Veshovda
site_dir: _site

# Repository
#repo_name: Testing MKDocs
repo_url: https://github.com/fancydrones/x500-rpi4
edit_uri: edit/main/docs
docs_dir: docs

# Navigation
nav:
  - Intro: README.md
  - BOM: bom.md
  - Software:
    - Install Software: software.md
    - OS: os.md
    - Zerotier: zerotier.md
  - Gimbal: gimbal/README.md

## DO NOT CHANGE BELOW THIS LINE
# Theme
theme:
  name: material
  icon:
    logo: material/helicopter
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - navigation.tracking
  palette:
    scheme: default
    primary: blue
    accent: blue

# Plugins
plugins:
  - search
  - glightbox

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - meta
  - mdx_math:
      enable_dollar_delimiter: True
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
