# Project information
site_name: Fancydrones X500 RPi4
site_url: https://fancydrones.github.io/x500-rpi4/
site_author: Fancydrones // Roy Veshovda
site_dir: _site

# Repository
#repo_name: Testing MKDocs
repo_url: https://github.com/fancydrones/x500-rpi4
edit_uri: edit/main/docs
docs_dir: docs

# Navigation
nav:
  - Overview: README.md 

## DO NOT CHANGE BELOW THIS LINE
# Theme
theme:
  name: material
  icon:
    logo: material/library
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - navigation.tracking
  palette:
    scheme: default
    primary: blue
    accent: blue

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
