# Project information
site_name: Fancydrones X500 RPi4
site_url: https://fancydrones.github.io/x500-cm4/
site_author: Fancydrones // Roy Veshovda
site_dir: _site
edit_uri: 'blob/main/docs/'

# Repository
repo_url: https://github.com/fancydrones/x500-cm4
docs_dir: docs

# Navigation
nav:
  - X500-CM4: README.md
  - BOM: bom.md
  - Software:
    - Install Software: software.md
    - OS: os.md
    - Zerotier: zerotier.md
  - Gimbal: gimbal/README.md

## DO NOT CHANGE BELOW THIS LINE
# Theme
theme:
  name: material
  icon:
    logo: material/helicopter
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - navigation.tracking
    - emoji_svg
  palette:
    # Documented here: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

# Plugins
plugins:
  - search
  - glightbox
  #- privacy - only available for Insiders

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - tables
  - meta
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: material/helicopter
      link: https://fancydrones.github.io
      name: Fancydrones Designs
