# Project information
site_name: Fancydrones X500 RPi4
site_url: https://fancydrones.github.io/x500-rpi4/
site_author: Fancydrones // Roy Veshovda
site_dir: _site

# Repository
#repo_name: Testing MKDocs
repo_url: https://github.com/fancydrones/x500-rpi4
edit_uri: edit/main/docs
docs_dir: docs

# Navigation
nav:
  - Intro: README.md
  - BOM: bom.md
  - Software:
    - Install Software: software.md
    - OS: os.md
    - Zerotier: zerotier.md
  - Gimbal: gimbal/README.md

## DO NOT CHANGE BELOW THIS LINE
# Theme
theme:
  name: material
  icon:
    logo: material/helicopter
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - navigation.tracking
  palette:
    scheme: default
    primary: blue
    accent: blue

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
