---
apiVersion: v1
kind: Service
metadata:
  name: companion-service
spec:
  ports:
    - port: 4000
      protocol: TCP
  selector:
    app:  companion-deployment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: companion-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: companion-service
            port:
              number: 4000