apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: companion
  name: companion
  namespace: rpiuav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: companion-strategy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: companion-strategy
    spec:
      containers:
      - env:
        - name: PHX_SERVER
          value: "True"
        - name: SECRET_KEY_BASE
          value: GM4Nv3AsIrj36aK6y2NJYmuKZSKoJ9i5bjxaLSLTH+2A16LC69JzQzHe7X3m7YJR
        - name: MAVLINK_CONNECTION
          value: udpout:127.0.0.1:14550
        image: registry.gitlab.com/got.vision/rpiuav/companion:1.0.120
        name: companion-strategy
        ports:
        - containerPort: 4000
        volumeMounts:
        - mountPath: /var/lib/rancher/k3s/server/tls/server-ca.crt
          name: ca
      hostNetwork: true
      serviceAccountName: rpimodifier
      volumes:
      - hostPath:
          path: /var/lib/rancher/k3s/server/tls/server-ca.crt
        name: ca
