apiVersion: v1
kind: Service
metadata:
  name: companion-service
  namespace: rpiuav
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4000
  selector:
    app.kubernetes.io/name: companion-deployment
