apiVersion: v1
kind: Service
metadata:
  name: streamer-service
  namespace: rpiuav
spec:
  type: NodePort
  ports:
  - port: 8554
    protocol: TCP
    targetPort: 18554
    nodePort: 8554
  selector:
    app.kubernetes.io/name: streamer-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: streamer-deployment
    name: streamer
  name: streamer
  namespace: rpiuav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer-replicaset
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: streamer-deployment
        app: streamer-replicaset
    spec:
      containers:
      - env:
        - name: CAMERA_PIPELINE0
          valueFrom:
            configMapKeyRef:
              key: STREAMER_CAMERA_PIPELINE0
              name: rpi4-config
        - name: VIDEO_PORT
          value: "8554"
        image: registry.gitlab.com/got.vision/rpiuav/streamer:2022-08-10.261
        name: streamer
        ports:
        - containerPort: 18554
        resources:
          limits:
            cpu: "2"
            memory: 2500Mi
          requests:
            cpu: "1"
            memory: 500Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run/udev
          name: udev
      volumes:
      - hostPath:
          path: /run/udev
        name: udev
