apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: streamer
  name: streamer
  namespace: rpiuav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer-replicaset
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: streamer-replicaset
    spec:
      containers:
      - env:
        - name: CAMERA_PIPELINE0
          valueFrom:
            configMapKeyRef:
              key: STREAMER_CAMERA_PIPELINE0
              name: rpi4-config
        - name: VIDEO_PORT
          value: "8554"
        image: registry.gitlab.com/got.vision/rpiuav/streamer:2022-07-27.223
        name: streamer
        ports:
        - containerPort: 8554
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run/udev
          name: udev
        resources:
          requests:
            memory: "500Mi"
            cpu: "1"
          limits:
            memory: "2500Mi"
            cpu: "2"
      hostNetwork: true
      volumes:
      - hostPath:
          path: /run/udev
        name: udev
