apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mavision-streamer
  name: mavision-streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mavision-streamer-recreate-strategy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mavision-streamer-recreate-strategy
    spec:
      containers:
      - env:
        - name: CAMERA_PIPELINE0
          value: libcamerasrc ! video/x-raw,width=1280,height=720,format=NV12,colorimetry=bt601,interlace-mode=progressive
            ! videoflip video-direction=180 ! videorate ! video/x-raw,framerate=30/1
            ! v4l2convert ! v4l2h264enc output-io-mode=2 extra-controls="controls,repeat_sequence_header=1,video_bitrate_mode=1,h264_profile=3,video_bitrate=5000000"
            ! video/x-h264,profile=main,level=(string)4 ! queue max-size-buffers=1
            name=q_enc ! h264parse ! rtph264pay config-interval=1 name=pay0 pt=96
        - name: VIDEO_PORT
          value: "8554"
        image: registry.gitlab.com/got.vision/rpiuav/streamer:1.0.15
        name: mavision-streamer-recreate-strategy
        ports:
        - containerPort: 8554
        volumeMounts:
        - mountPath: /run/udev
          name: udev
      hostNetwork: true
      volumes:
      - hostPath:
          path: /run/udev
        name: udev
