kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: rpiuav
  name: modify-and-restart
rules:
- apiGroups: ["apps", "extensions"]
  resources: ["deployments"]
  verbs: ["get", "patch", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "patch", "list", "watch"]
