kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: testadminbinding
  namespace: rpiuav
subjects:
- kind: ServiceAccount
  name: rpimodifier
  apiGroup: ""
roleRef:
  kind: Role
  name: modify-and-restart
  apiGroup: ""