kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: rpiuav
  name: metrics-role
rules:
- apiGroups: ["metrics.k8s.io/v1beta1"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
