kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics-rb
subjects:
- kind: ServiceAccount
  name: rpimodifier
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: metrics-role
  apiGroup: ""