apiVersion: v1
kind: ConfigMap
metadata:
  name: rpi4-config
  namespace: rpiuav
data:
  ANNOUNCER_CAMERA_URL: rtsp://10.10.10.2:8554/video
  ANNOUNCER_SYSTEM_ID: "1"
  STREAMER_CONFIG: |
    paths:
      cam:
        source: rpiCamera
        rpiCameraWidth: 1280
        rpiCameraHeight: 720
        rpiCameraVFlip: true
        rpiCameraHFlip: true
  ROUTER_CONFIG: |
    [General]
    # Print traffic statistics to stdout
    # Default: <false>
    ReportStats=false

    # Logging verbosity (stderr)
    # Valid values: <error>, <warning>, <info> or <debug>
    # Default: <info>
    #DebugLogLevel = info

    #Mavlink-router serves on this TCP port
    TcpServerPort=5760

    MavlinkDialect=auto

    [UartEndpoint FlightControllerSerial]
    Device = /dev/serial0
    Baud = 921600

    [UdpEndpoint FlightControllerUDP]
    Mode = Server
    Address = 0.0.0.0
    Port = 14555

    [UdpEndpoint video0]
    Mode = Server
    Address = 0.0.0.0
    Port = 14560
    AllowMsgIdOut = 0,4,76,322,323

    [UdpEndpoint video1]
    Mode = server
    Address = 0.0.0.0
    Port = 14561
    AllowMsgIdOut = 0,4,76,322,323

    [UdpEndpoint GCS]
    Mode = Normal
    Address = 10.10.10.70
    Port = 14550
