---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-infra
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/fancydrones/x500-cm4
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: rpi4
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deployments
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-infra