name: Announcer image

on:
  push:
    branches: ['main']
    paths:
      - 'apps/announcer/**'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  process-image:
    uses: ./.github/workflows/process-image-template.yaml
    with:
      app_name: announcer
      platforms: linux/arm64
