name: Video Streamer image

on:
  push:
    branches: ["main"]
    paths:
      - "apps/video_streamer/**"
      - ".github/workflows/process-video-streamer.yaml"
      - ".github/workflows/process-image-template.yaml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  process-image:
    uses: ./.github/workflows/process-image-template.yaml
    with:
      app_name: video-streamer
      runner_label: ubuntu-arm-latest-m
    secrets: inherit
