name: Create, publish and release Announcer image

on:
  push:
    branches: ['main']

jobs:
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/process-image-template.yaml
    with:
      platforms: linux/amd64,linux/arm64
      registry: ghcr.io
      image_name: ${{ github.repository }}/announcer
      app_context: apps/announcer
      image_title: Announcer
      image_description: FancyDrones X500-RPi4 Announcer
      image_vendor: FancyDrones
