name: Companion image

on:
  push:
    branches: ['main']
    paths:
      - 'apps/companion/**'
      - '.github/workflows/process-companion.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  process-image:
    uses: ./.github/workflows/process-image-template.yaml
    with:
      app_name: companion
      platforms: linux/amd64,linux/arm64
