name: Announcer image

on:
  push:
    branches: ['main']
    paths:
      - 'apps/announcer/**'

jobs:
  process-image:
    uses: ./.github/workflows/process-image-template.yaml
    with:
      platforms: linux/amd64,linux/arm64
      app_name: announcer
