name: Reusable image Create, publish and release

on:
  workflow_call:
    inputs:
      platforms:
        required: true
        type: string
      app_name:
        required: true
        type: string

env:
  KUSTOMIZE_VER: 4.5.7
  APPS_PATH: deployments/apps
  REGISTRY: ghcr.io
  IMAGE_VENDOR: FancyDrones
  IMAGE_CONTEXT: X500-CM4

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      version_tag: ${{ env.datetag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ inputs.platforms }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ inputs.platforms }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get image date tag
        id: tag
        run: |
          datetag=$(date +'%Y%m%d')-${GITHUB_SHA::7}
          echo "datetag=$datetag" >> $GITHUB_ENV
          echo "datetag=$datetag" >> $GITHUB_OUTPUT
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ inputs.app_name }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ env.datetag }}
          labels: |
            org.opencontainers.image.title=${{ inputs.app_name }}
            org.opencontainers.image.description=${{ env.IMAGE_VENDOR }} ${{ env.IMAGE_CONTEXT }} ${{ inputs.app_name }}
            org.opencontainers.image.vendor=${{ env.IMAGE_VENDOR }}
            org.opencontainers.image.version=${{ env.datetag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: apps/${{ inputs.app_name }}
          platforms: ${{ inputs.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  update-deployment:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare Kustomize
        run: |
          echo "before"
          curl -L https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VER}/kustomize_v${KUSTOMIZE_VER}_linux_amd64.tar.gz -o kustomize.tar.gz
          tar -xvzf kustomize.tar.gz && chmod +x ./kustomize
      - name: "Patch"
        run: |
          rm kustomization.yaml -f
          ./kustomize create
          ./kustomize edit set image ${{ env.REGISTRY }}/${{ github.repository }}/${{ inputs.app_name }}:${{ needs.build-and-push-image.outputs.version_tag }}
          ./kustomize edit add resource $APPS_PATH/${{ inputs.app_name }}-deployment.yaml
          ./kustomize build . > x.yaml
          cat x.yaml
          mv x.yaml $APPS_PATH/${{ inputs.app_name }}-deployment.yaml
          rm kustomization.yaml
      - name: Commit update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "New version: ${{ env.REGISTRY }}/${{ github.repository }}/${{ inputs.app_name }}:${{ needs.build-and-push-image.outputs.version_tag }}"
          git pull --rebase=true
          git push
