name: Streamer image

on:
  push:
    branches: ['main']

jobs:
  process-image:
    uses: ./.github/workflows/process-image-template.yaml
    with:
      platforms: linux/arm64
      app_name: streamer
