name: Companion image

on:
  workflow_dispatch:
  # push:
  #   branches: ['main']

jobs:
  process-image:
    uses: ./.github/workflows/process-image-template.yaml
    with:
      platforms: linux/amd64,linux/arm64
      app_name: companion
