name: Announcer image

on:
  push:
    branches: ['main']
    paths:
      - 'apps/announcer/**'
      - '.github/workflows/process-announcer.yaml'
      - '.github/workflows/process-image-template.yaml'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  process-image:
    uses: ./.github/workflows/process-image-template.yaml
    with:
      app_name: announcer
      runner_label: ubuntu-arm-latest-m
